name: GitHub Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Debug Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Clear npm cache and reinstall dependencies
        run: |
          npm cache clean --force
          npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
